Repository AlexPasqua/NNs-from-scratch, pull requests merged in 2020-12, with the labels that each got.

#15 unit_test for class Network
  .github/workflows/tests.yml
  src/test_network.py
Labels: refactor

#21 Layer weights
  screenshot_wikipedia.jpg
  src/network.py
  src/optimizers.py
Labels: enhancement

#25 Fixed setter of Layer's weights
  src/network.py
Labels: bug

#26 Output layer weights update
  src/network.py
  src/optimizers.py
Labels: bugfix

#29 Weights initialization
  src/activation_functions.py
  src/network.py
  src/tests/test_network.py
  src/tests/test_weights_inits.py
  src/weights_inits.py
Labels: enhancement

#30 Merge backprop into develop
  src/network.py
  src/optimizers.py
Labels: enhancement

#31 Training loop now runs with many patterns
  src/network.py
  src/optimizers.py
  src/tests/test_network.py
Labels: bugfix, enhancement

#33 Backprop now updates biases
  src/network.py
  src/optimizers.py
Labels: bugfix, enhancement

#32 MSE created and tested. (works for all patterns)
  src/error_functions.py
  src/losses.py
  src/tests/test_error_functions.py
Labels: enhancement

#35 Fixed bias update and improved backprop
  src/losses.py
  src/network.py
  src/optimizers.py
  src/tests/test_network.py
Labels: bugfix, enhancement

#41 Momentum implemented
  plots/accuracy_24-12-2020.png
  plots/accuracy_momentum_24-12-2020.png
  plots/loss_24-12-2020.png
  plots/loss_momentum_24-12-2020.png
  src/functions.py
  src/monk_demo.py
  src/network/network.py
  src/optimizers.py
  src/unit_tests/test_network.py
  src/unit_tests/test_optimizers.py
Labels: enhancement

#44 Momentum parameter checks and unit-tests
  src/monk_demo.py
  src/network/network.py
  src/unit_tests/test_network.py
Labels: enhancement

#42 Linear decay learning rate
  src/functions.py
  src/monk_demo.py
  src/network/network.py
  src/optimizers.py
  src/unit_tests/test_function.py
  src/unit_tests/test_optimizers.py
Labels: enhancement

#45 Cross validation
  src/model_selection.py
  src/monk_demo.py
  src/network/layer.py
  src/network/network.py
  src/optimizers.py
  src/unit_tests/test_layer.py
  src/unit_tests/test_network.py
  src/unit_tests/test_optimizers.py
  src/unit_tests/test_unit.py
  src/unit_tests/test_weights_initializations.py
  src/weights_initializations.py
Labels: enhancement

#46 Hold-out validation
  plots/accuracy_24-12-2020.png
  plots/accuracy_momentum_24-12-2020.png
  plots/loss_24-12-2020.png
  plots/loss_momentum_24-12-2020.png
  plots/monk1_train.png
  plots/monk1_train_holdout-val.png
  plots/monk2_train_holdout-val.png
  src/model_selection.py
  src/monk_demo.py
  src/network/network.py
  src/optimizers.py
  src/unit_tests/test_network.py
Labels: enhancement
