Repository AlexPasqua/NNs-from-scratch, pull requests merged in 2021-01, with the labels that each got.

#48 Exploited matrices + optimization
  .github/workflows/tests.yml
  src/functions.py
  src/monk_demo.py
  src/network/layer.py
  src/network/network.py
  src/network/unit.py
  src/optimizers.py
  src/unit_tests/test_function.py
  src/unit_tests/test_layer.py
  src/unit_tests/test_network.py
  src/unit_tests/test_optimizers.py
  src/unit_tests/test_weights_initializations.py
  src/weights_initializations.py
Labels: enhancement, refactor

#50 Utility
  src/monk_demo.py
  src/utility.py
Labels: enhancement

#51 Added identity activation function
  src/functions.py
  src/unit_tests/test_function.py
Labels: enhancement

#52 Datasets shuffle happens only if not full batch
  src/monk_demo.py
  src/optimizers.py
Labels: question

#56 Expo decay
  src/functions.py
  src/model_selection.py
  src/monks_demo.py
  src/network.py
  src/optimizers.py
  src/unit_tests/test_network.py
  src/unit_tests/test_optimizers.py
  src/utility.py
Labels: enhancement

#58 Manage warnings in cross_valid
  results/results.json
  results/results_cup.json
  src/cup_demo.py
  src/functions.py
  src/model_selection.py
  src/network.py
  src/utility.py
Labels: bugfix, enhancement

#60 predict & evaluate
  results/results_monks-1.train.json
  src/layer.py
  src/model_selection.py
  src/monks_demo.py
  src/network.py
  src/optimizers.py
  src/utility.py
Labels: bugfix, enhancement

#61 - added missing documentation in functions.py
  src/functions.py
Labels: documentation
